version: 1
env:
  loop: true
  loop_times: 0
  log: true
  name: "book"
  # 开启弹幕监听，开启此功能，后续才可以使用on_barrage_received字段
  enable_barrage_monitoring: true
jobs:
  开场白:
    type: audio
    name: 开场白
    value: 大家好，欢迎来到今天的阅月读书时光直播间！我是你们的朋友，阅月。在接下来的两个小时里，我将带领大家走进书籍的世界，一起探索那些让人无法放下的畅销书。今天我们精心挑选了10本不同领域的热门书籍，无论是文学爱好者、商业人士还是科技迷，总有一本会触动你的心弦。准备好了吗？让我们一起开始今天的书海之旅吧！
    caption: 开场白
    background_music: "[充满魔法的背景音乐]"
    background_image: "C:/Users/wukai/Downloads/直播透明背景.png"
  one_part:
    type: group
    name: 第一部分：畅销书推荐
    background_image: "C:/Users/wukai/Downloads/1-图书推荐.png"
    on_barrage_received:
      action: 'play_audio'
      opportunity: 'after_job_executed'
      # 解析的任务深度，如果为-1，则所有任务都可能响应此动作，如果为0，代表当前任务（不解析任何子任务），设置为正整数，那么会解析第n层的子任务（如果存在），例如这里设置为1，意为在每本图书执行完毕时，检查是否有弹幕然后执行相应操作
      deep: -1
      play_audio:
        type: audio
        name: '有弹幕时的过度内容'
        value: '感谢小伙伴的弹幕讨论，为保证直播内容的完整性，我们在后面的部分设置有讨论环节，现在先允许我继续介绍哦'
    jobs:
      1:
        type: group
        name: 《追风筝的人》卡勒德·胡赛尼
        caption: 《追风筝的人》卡勒德·胡赛尼
        background_music: "[充满魔法的背景音乐]"
        jobs:
          开始:
            name: 开始
            type: audio
            value: 亲爱的读者朋友们，大家好！今天，我为大家带来一本深触动人心弦、来自阿富汗的作家卡勒德·胡赛尼的作品——《追风筝的人》。这不仅仅是一本书，它更像是一段跨越时空的心灵之旅。
          书籍介绍:
            name: 书籍介绍
            type: audio
            value: 《追风筝的人》讲述了一个关于友谊、背叛与救赎的故事。故事的主角阿米尔，一个生活在喀布尔的帕什图族富家少年，与他忠实的哈扎拉族朋友哈桑之间的友情，以及后来的种种经历，描绘了一个关于人性深层次的纠葛。在阿富汗动荡不安的历史背景下，他们的命运如何相互纠缠，让人深感震撼。
          内容概要:
            name: 内容概要
            type: audio
            value: 在这本书中，我们跟随阿米尔见证了他与哈桑之间关系的起伏，从童年无忧无虑的放风筝日子，到命运将他们残酷分开的那一刻开始，阿米尔的内心世界也随之四分五裂。他的内疚、自责，以及对朋友的背叛感到的痛苦，这些情感贯穿了整本书。而当阿米尔有了救赎自己的机会时，我们看到的是勇气、忠诚与爱的力量。
          推荐理由:
            name: 推荐理由
            type: audio
            value: 我之所以向大家推荐《追风筝的人》，不仅因为它扣人心弦的故事情节，更因为胡赛尼先生如何通过文字让我们深切地感受到人性的复杂和微妙。这本书能够唤起人们对于忠诚、友情与爱的思考，同时，它也是对历史的一种反思，提醒我们珍惜和平与拥有的一切。
          读者评论分享:
            name: 读者评论分享
            type: audio
            value: 许多读者在阅读后都表达了对这本书的深刻感动。有人说，“《追风筝的人》是一本能够让人重新审视自己生活的书。”也有读者认为，“它不仅是一段旅程，更是一次心灵的洗礼。”
          互动提问:
            name: 互动提问
            type: audio
            value: 现在，我很想知道，听完我的介绍，你们是否已经被《追风筝的人》吸引了呢？或者，你有没有类似感人的故事书推荐给我们呢？请在下方评论区与我分享你的想法，我会在直播中为大家逐一回复。
          结束:
            name: 结束
            type: audio
            value: 好了，亲爱的朋友们，如果你被《追风筝的人》的故事所打动，或是想要体验这段心灵旅程，请不要犹豫，现在就通过直播专属链接进行购买。同时，告诉你的亲朋好友，一起分享阅读的喜悦吧！
      2:
        type: group
        name: 《解忧杂货店》东野圭吾
        caption: 《解忧杂货店》东野圭吾
        background_music: "[轻快的科技感音乐作背景]"
        jobs:
          开始:
            name: 开始
            type: audio
            value: 今天我们要介绍的第二本书是来自日本作家东野圭吾的《解忧杂货店》。这是一部温暖人心的作品，它以一家看似普通的杂货店为线索，织出了一个个充满魔力的故事。
          书籍介绍:
            name: 书籍介绍
            type: audio
            value: 《解忧杂货店》讲述了一家名为“解忧杂货店”的神秘小店，通过回信的方式解决人们的各种烦恼。无论是爱情、家庭、学业还是工作上的问题，只需写信告知，隔天即可在牛奶箱中得到解答。
          内容概要:
            name: 内容概要
            type: audio
            value: 书中通过三个年轻人无意中闯入杂货店并成为解答者的故事，展现了人内心深处的善良与恶意，以及面对困境时的不同选择。通过一封封充满私人困扰的信件和店主精心的回复，展现了人性的复杂和希望的力量。
          推荐理由:
            name: 推荐理由
            type: audio
            value: 《解忧杂货店》不仅仅是一本小说，它像是生活的缩影，提醒我们每个人的生活中都有着不同形式的困扰和难题，重要的是我们如何面对和解决它们。这本书提供了一种独特的视角来观察人性和人生，让人在阅读后深感温暖和希望。
          读者评论分享:
            name: 读者评论分享
            type: audio
            value: 很多读者都被这本书深深触动，认为它是一本能够治愈心灵的书。一位读者这样写道，“每次感到孤独或困惑时，我都会想起《解忧杂货店》中的故事，它让我明白，无论何时，总有人愿意倾听你的心声。”
          互动提问:
            name: 互动提问
            type: audio
            value: 那么，对于这种带有治愈属性的书籍，你们是不是也有特别喜欢的一本书呢？它给你带来了怎样的感动或启示？请在评论区与我分享你的故事。
          结束:
            name: 结束
            type: audio
            value: 如果你被《解忧杂货店》的故事所吸引，现在通过直播专属链接购买还可以享受优惠。快来获取你的治愈之书，让心灵得到温暖的抚慰吧！
#      3:
#        type: group
#        name: 《人类简史》尤瓦尔·赫拉利
#        caption: 《人类简史》尤瓦尔·赫拉利
#        background_music: "[启发思考的背景音乐]"
#        jobs:
#          开始:
#            name: 开始
#            type: audio
#            value: 各位读者朋友们，接下来为大家推荐的是尤瓦尔·赫拉利的《人类简史》。这本书不仅仅是历史的回顾，更是对人类社会和文明的深刻洞察。
#          书籍介绍:
#            name: 书籍介绍
#            type: audio
#            value: 《人类简史》从一个全新的视角审视了人类的过去、现在和未来。作者赫拉利以生物学、人类学、历史学等多个学科的角度，探索了人类从古至今的发展过程，及其对地球的影响。
#          内容概要:
#            name: 内容概要
#            type: audio
#            value: 书中涵盖了人类历史上的重大转折点，包括认知革命、农业革命、科学革命等，讨论了货币、帝国、宗教、文化和资本主义等概念是如何塑造现今社会的。
#          推荐理由:
#            name: 推荐理由
#            type: audio
#            value: 推荐《人类简史》的原因在于它能够扩展我们的视野，让我们不仅仅局限于自己所在的时间和空间，而是从更宏观的角度理解人类的行为和社会发展。这本书对于想要了解人类以及我们自己在过去、现在和未来所扮演角色的读者来说，是一本不可多得的好书。
#          读者评论分享:
#            name: 读者评论分享
#            type: audio
#            value: 有读者评价说，“《人类简史》不仅让我了解了人类的历史，更重要的是让我思考了我们未来的方向。”
#          互动提问:
#            name: 互动提问
#            type: audio
#            value: 大家是不是也在阅读这本书时产生了一些对人类社会和未来发展的思考呢？欢迎在评论区分享你的想法和感悟。
#          结束:
#            name: 结束
#            type: audio
#            value: 现在通过直播的链接购买《人类简史》，你可以享有不菲的折扣。让我们一起跟随尤瓦尔·赫拉利，开启一段思考人类过去和未来的旅程吧！
#      4:
#        type: group
#        name: 《哈利·波特与魔法石》J.K.罗琳
#        caption: 《哈利·波特与魔法石》J.K.罗琳
#        background_music: "[充满魔法的背景音乐]"
#        jobs:
#          开始:
#            name: 开始
#            type: audio
#            value: 大家好，欢迎回到《阅月图书推荐》，今天我们将一起走进充满魔法的世界——来自J.K.罗琳的《哈利·波特与魔法石》。
#          书籍介绍:
#            name: 书籍介绍
#            type: audio
#            value: 这不仅仅是一个关于魔法的故事，更是关于成长、勇气与友谊的叙述。书中描述了主人公哈利·波特在霍格沃茨魔法学校的冒险经历，以及与朋友们一起对抗黑暗势力的故事。
#          内容概要:
#            name: 内容概要
#            type: audio
#            value: 在接收到霍格沃茨的入学通知书后，哈利波特踏上了不一样的人生旅程。在那里，他结识了终生的好友，学会了使用魔法，同时也揭开了自己过去的秘密。
#          推荐理由:
#            name: 推荐理由
#            type: audio
#            value: 《哈利·波特与魔法石》是一系列令人着迷的书中的第一部，它不仅吸引了无数年轻读者，也成为了成年人心中的魔法世界。这本书激发了我们的想象力，同时教会我们勇敢面对困难，珍视友谊。
#          读者评论分享:
#            name: 读者评论分享
#            type: audio
#            value: 许多读者说，《哈利·波特与魔法石》陪伴了他们的成长，它不仅仅是一本书，更是他们美好记忆中的一部分。
#          互动提问:
#            name: 互动提问
#            type: audio
#            value: 我想知道，有多少观众是哈利·波特系列的粉丝？你们的魔法世界是什么样的？快在评论区和我分享吧！
#          结束:
#            name: 结束
#            type: audio
#            value: 若你对这个充满魔法与奇迹的世界感兴趣，现在正是收藏这套经典之作的好时机。通过直播专属链接购买，你将得到特别的折扣。不要错过，让魔法照亮你的现实生活吧！
#      5:
#        type: group
#        name: 《活着》余华
#        caption: 《活着》余华
#        background_music: "[充满魔幻色彩的音乐作背景]"
#        jobs:
#          开始:
#            name: 开始
#            type: audio
#            value: 欢迎回到《阅月图书推荐》。今天我要给大家介绍的是余华的经典之作——《活着》。这是一部深刻揭示人生真谛、让无数读者泪目的作品。
#          书籍介绍:
#            name: 书籍介绍
#            type: audio
#            value: 《活着》讲述了主人公福贵跌宕起伏的一生。他经历了从家财万贯到一贫如洗的转变，亲眼目睹了家人在各种社会变革和自然灾害中一个接一个地离他而去，但即便如此，福贵依然选择坚强地活下去。
#          内容概要:
#            name: 内容概要
#            type: audio
#            value: 这本书通过福贵的故事，展现了生命的脆弱与坚韧，以及在极端困境下人性的光辉。尽管生活给予了福贵无尽的打击，但他对于生活的热爱和对家人的思念，让他选择了继续活下去。
#          推荐理由:
#            name: 推荐理由
#            type: audio
#            value: 《活着》是一本让人深思的书，它不仅仅是福贵个人悲剧的展现，更是对生活本质的探讨。它教会我们珍惜眼前人，珍惜所拥有的一切，因为生命不可复得，生活本身就是最大的财富。
#          读者评论分享:
#            name: 读者评论分享
#            type: audio
#            value: 很多读者读后感慨万分，有人说：“《活着》是一部让人重新认识生活、感悟人生的好书。它让我懂得了何为活着，何为珍贵。”
#          互动提问:
#            name: 互动提问
#            type: audio
#            value: 我非常想知道，大家对《活着》有什么样的看法？它是否触动了你的心灵，改变了你对生活的看法？请在评论区与我分享你的感受和经历。
#          结束:
#            name: 结束
#            type: audio
#            value: 如果你被福贵的故事所触动，现在通过直播专属链接购买《活着》，你可以享受到特别的优惠。把握机会，让这本书成为你生命中的一部份吧！
#      6:
#        type: group
#        name: 《百年孤独》加西亚·马尔克斯
#        caption: 《百年孤独》加西亚·马尔克斯
#        background_music: "[充满魔幻色彩的音乐作背景]"
#        jobs:
#          开始:
#            name: 开始
#            type: audio
#            value: 大家好，今天我们将一起探索加西亚·马尔克斯的杰作——《百年孤独》。这是一部融合了现实与魔幻、幻想与历史的小说，讲述了布恩迪亚家族七代人的传奇故事。
#          书籍介绍:
#            name: 书籍介绍
#            type: audio
#            value: 《百年孤独》发生在一个虚构的小镇马孔多，通过布恩迪亚家族的经历，描绘了拉丁美洲的历史和文化。这个家族的每一代人都重复着前人的悲剧，仿佛被诅咒，无法逃离孤独的命运。
#          内容概要:
#            name: 内容概要
#            type: audio
#            value: 在这本书中，现实与奇幻交织，时间似乎在马孔多停滞不前。作者通过丰富的想象力和精湛的文笔，展现了一个令人着迷的世界，同时也反映了人性的复杂和多样性。
#          推荐理由:
#            name: 推荐理由
#            type: audio
#            value: 《百年孤独》被誉为20世纪最伟大的文学作品之一。它不仅因其独特的文风和丰富的想象力受到推崇，更因为它深刻揭示了人类孤独、命运和历史的循环往复。这本书是对生的热爱，对死的冥想，对永恒的追求。
#          读者评论分享:
#            name: 读者评论分享
#            type: audio
#            value: 许多读者表示，《百年孤独》改变了他们的阅读习惯，甚至影响了他们的人生观。一位读者曾说：“在马尔克斯的世界里，我找到了对生命和爱情的深刻理解。”
#          互动提问:
#            name: 互动提问
#            type: audio
#            value: 那么，你们有没有读过让你对生活有了全新认识的书呢？或者《百年孤独》给你带来了哪些启示？欢迎在评论区与我分享。
#          结束:
#            name: 结束
#            type: audio
#            value: 如果你被《百年孤独》的魔幻世界吸引，现在正是收藏这部作品的好时机。通过直播专属链接购买，享受折扣优惠。让我们一起在马孔多的世界中寻找生命的意义吧！
#      7:
#        type: group
#        name: 《失控》凯文·凯利
#        caption: 《失控》凯文·凯利
#        background_music: "[神秘而充满科技感的背景音乐]"
#        jobs:
#          开始:
#            name: 开始
#            type: audio
#            value: 各位读者朋友们，今天给大家带来的是凯文·凯利的《失控》。这不仅仅是一本书，更是一次对未来社会、科技与生活的深刻洞察。
#          书籍介绍:
#            name: 书籍介绍
#            type: audio
#            value: 《失控》探讨了技术进步如何影响人类的生活方式、工作方式和社会结构。凯利通过对蜂群行为的研究，探索了群体智慧和去中心化系统的可能性，并预测了未来社会的发展趋势。
#          内容概要:
#            name: 内容概要
#            type: audio
#            value: 书中以独特的视角分析了自然界和人造系统中的去中心化现象，从蜂群到互联网，再到全球经济，凯利指出，失控并非意味着混乱，而是更高层次的秩序与创新的源泉。
#          推荐理由:
#            name: 推荐理由
#            type: audio
#            value: 推荐《失控》的原因在于其前瞻性的思维和深邃的见解。在当今快速发展的科技时代，了解和掌握这些概念至关重要。这本书能启发我们思考如何与技术和谐共存，如何在变革中找到我们的位置。
#          读者评论分享:
#            name: 读者评论分享
#            type: audio
#            value: 有读者评论说，《失控》就像是一本未来学手册，帮助他们在看似混乱的世界中找到了方向和希望。
#          互动提问:
#            name: 互动提问
#            type: audio
#            value: 我很好奇，大家对《失控》这本书有什么看法？它是否改变了你对技术和社会的看法？欢迎在评论区与我分享你的想法。
#          结束:
#            name: 结束
#            type: audio
#            value: 现在通过直播专属链接购买《失控》，你将享有特别优惠。让我们一起跟随凯文·凯利的思路，探索在快速变化中寻找平衡的方法吧！
#      8:
#        type: group
#        name: 《未来简史》尤瓦尔·赫拉利
#        caption: 《未来简史》尤瓦尔·赫拉利
#        background_music: "[充满未来感的电子音乐作背景]"
#        jobs:
#          开始:
#            name: 开始
#            type: audio
#            value: 各位读者朋友们，接下来为大家推荐的是尤瓦尔·赫拉利的又一力作——《未来简史》。继《人类简史》后，赫拉利再次以独特的视角审视人类的未来。
#          书籍介绍:
#            name: 书籍介绍
#            type: audio
#            value: 《未来简史》探讨了人类社会、经济、科技和文化等方面可能发生的变化。赫拉利以批判的眼光分析了现代科技的发展，以及这些发展如何影响我们的生活和价值观。
#          内容概要:
#            name: 内容概要
#            type: audio
#            value: 书中讨论了人工智能、生物技术和数据主义等前沿话题，对人类面临的新挑战提出了预警，同时对幸福的真义和社会的道德责任提出了思考。
#          推荐理由:
#            name: 推荐理由
#            type: audio
#            value: 推荐《未来简史》是因为它能激发我们对未来的思考，帮助我们更好地准备迎接未来的挑战。赫拉利的观点虽然具有争议性，但无疑为我们提供了重要的视角来审视当下和未来的生活。
#          读者评论分享:
#            name: 读者评论分享
#            type: audio
#            value: 一些读者表示，《未来简史》让他们开始思考如何在科技迅速发展的时代中保持人性的本质，以及如何面对即将到来的社会变革。
#          互动提问:
#            name: 互动提问
#            type: audio
#            value: 那么，大家对《未来简史》有什么看法呢？它是否让你对未来有了不同的理解？快在评论区分享你的想法吧！
#          结束:
#            name: 结束
#            type: audio
#            value: 如果你对《未来简史》感兴趣，现在通过直播专属链接购买可以享受优惠。让我们跟随尤瓦尔·赫拉利的步伐，一起探索未来的可能性吧！
#      9:
#        type: group
#        name: 《智能时代》吴军
#        caption: 《智能时代》吴军
#        background_music: "[轻快的科技感音乐作背景]"
#        jobs:
#          开始:
#            name: 开始
#            type: audio
#            value: 各位读者朋友们，今天很高兴为大家介绍吴军的《智能时代》。这本书深入探讨了人工智能对我们社会的影响，以及我们应如何适应这一新时代。
#          书籍介绍:
#            name: 书籍介绍
#            type: audio
#            value: 《智能时代》详细解释了人工智能的发展历程、现状以及未来趋势。作者吴军博士以其深厚的技术背景和丰富的行业经验，为我们揭示了人工智能的未来可能带来的变革。
#          内容概要:
#            name: 内容概要
#            type: audio
#            value: 书中不仅讨论了人工智能在各行各业的应用，还分析了它对社会结构、就业市场、教育体系乃至个人生活的深远影响。吴军博士强调了在智能时代，我们需要更新观念，积极适应并利用新技术。
#          推荐理由:
#            name: 推荐理由
#            type: audio
#            value: 《智能时代》是一本非常及时的书，它不仅能帮助我们理解人工智能技术本身，更重要的是能让我们思考如何在智能化浪潮中保持自身的竞争力。这本书适合所有对未来充满好奇心的读者。
#          读者评论分享:
#            name: 读者评论分享
#            type: audio
#            value: 很多读者都表示，《智能时代》让他们对人工智能有了更清晰的认识，也为他们的职业发展提供了宝贵的指导。
#          互动提问:
#            name: 互动提问
#            type: audio
#            value: 不知道大家读完《智能时代》后有什么感想？它是否改变了你对人工智能或未来工作和生活的看法？欢迎在评论区分享你的想法。
#          结束:
#            name: 结束
#            type: audio
#            value: 若你想更深入地了解人工智能及其对未来的影响，现在通过直播专属链接购买《智能时代》，你将享受到优惠价格。让我们一起迎接智能时代的挑战吧！
#      10:
#        type: group
#        name: 《富爸爸穷爸爸》罗伯特·T·清崎
#        caption: 《富爸爸穷爸爸》罗伯特·T·清崎
#        background_music: [启发思考的背景音乐]
#        jobs:
#          开始:
#            name: 开始
#            type: audio
#            value: 亲爱的读者们，接下来要介绍的是罗伯特·T·清崎的《富爸爸穷爸爸》。这本书改变了无数人的财务观念，引导他们走向财务自由。
#          书籍介绍:
#            name: 书籍介绍
#            type: audio
#            value: 《富爸爸穷爸爸》通过作者亲身经历的两个“爸爸”——一个是亲生父亲（穷爸爸），一个是朋友的父亲（富爸爸）——的故事，阐述了两种截然不同的财务观念和教育方式。
#          内容概要:
#            name: 内容概要
#            type: audio
#            value: 书中详细描述了富爸爸如何教导小罗伯特关于资产、负债、投资和理财的知识，以及穷爸爸传统的工作观念如何限制了财务上的成长。清崎强调，真正的财富来自资产的积累和投资，而非单纯的收入增加。
#          推荐理由:
#            name: 推荐理由
#            type: audio
#            value: 《富爸爸穷爸爸》是一本极具启发性的财务自助书。它不仅教会我们基本的财务知识，更重要的是，它改变了我们对金钱、投资和工作的传统看法，激励人们主动学习和掌握财务管理的技能。
#          读者评论分享:
#            name: 读者评论分享
#            type: audio
#            value: 很多读者表示，这本书让他们意识到了自己在财务上的误区，并开始规划自己的财务未来。一位读者这样写道：“《富爸爸穷爸爸》是我人生中的转折点，它让我开始了理财之路。”
#          互动提问:
#            name: 互动提问
#            type: audio
#            value: 我想知道，大家在读完《富爸爸穷爸爸》后有没有试着改变你的财务观念或行动？你们有没有实践过书中的建议？欢迎在评论区与我分享你的经验。
#          结束:
#            name: 结束
#            type: audio
#            value: 如果你被《富爸爸穷爸爸》的理念所吸引，现在通过直播专属链接购买可以享受优惠。开始你的财务自由之旅吧，让这本书成为你致富路上的启明星！
  second_part:
    name: 第二部分：特别话题讨论
    type: audio
    value: 阅读真的能够改变我们的生活，它能开阔我们的视野，提高我们的同理心。我个人非常喜欢在睡前读上几页，这有助于放松心情。你们有没有什么好的阅读习惯或心得想要跟大家分享？同时，我在这里也有几个阅读小贴士，比如制定阅读计划、选择适合的阅读环境等等。
  three_part:
    type: group
    name: 第三部分：互动与促销
    background_music: "[启发思考的背景音乐]"
    jobs:
      互动开始:
        type: audio
        name: "互动开场白"
        value: 我看到大家已经在评论区踊跃发言了，非常棒！现在让我们进入互动环节！
      互动:
        name: 互动
        type: interaction
        caption: "第三部分：互动与促销 - 互动提问，使用 #+问题，如 #你好 "
        duration: 1800
        idle_timing: 120
        idle_audios:
          1:
            type: audio
            name: "互动空闲时话术"
            value: "好了伙伴们，今天我们聊了阅读的那些事儿，那现在我们再一起来回顾一下前面介绍的十本畅销全球的书。今天我们推荐了能带你穿越时空，探索宇宙的奥秘的《时间简史》，温暖人心，治愈又感动的《解忧杂货店》，把人生的酸甜苦辣都写尽了的余华老师的《活着》，东野圭吾的悬疑大作《白夜行》，让你用全新视角看人类是怎么走过来的《人类简史》，讲述了一段关于友情、背叛和救赎的深刻故事的《追风筝的人》，魔幻现实主义的大作，文学经典《百年孤独》，对未来的思考《未来简史》，让你了解人工智能如何改变我们世界的《智能时代》，颠覆你的理财观念的《穷爸爸富爸爸》。相信每位朋友心中都有自己最喜欢的那一本，在此阅月也给大家带来史无前例的一次优惠折扣哦，现在只要在咱们直播间下单，这些畅销书都能享9.5折优惠哦！这种好事，千万别错过呀！对了，亲爱的朋友们，虽然阅读是个人的事，但分享感悟可是能让智慧加倍的哦。快在评论区告诉我，这些书给你带来了哪些启发？哪一本触动了你的心？咱们一起讨论吧，把阅读的快乐和收获分享给更多人。好了，今天参与活动的书籍有限，喜欢这些书的朋友，也记得抓紧时间享受折扣哦！"
        idle_start_audio:
          type: audio
          name: 口播过程中答复评论衔接语-出
          value: 好了。感谢小伙伴们的讨论，欢迎在评论区留言讨论哦，现在我们继续。
        idle_end_audio:
          type: audio
          name: 口播过程中答复评论衔接语-出
          value: 我看到评论区有小伙伴正在积极讨论。
  end:
    name: 结尾
    type: audio
    value:  时间总是飞逝，我们今天的书籍推荐就要结束了。非常感谢各位的陪伴，希望你们能从中找到心仪的书籍。记得利用剩下的时间抢购你喜欢的书！我们下次直播再见，敬请期待。再见，书友们！
    background_music: "[温馨而鼓舞人心的音乐作背景]"
  interval:
    name: 等待
    type: interval
    value: 10