version: 1
env:
  loop: true
  loop_times: 0
  log: true
  name: "book"
jobs:
  互动:
    name: 互动
    caption: "《追风筝的人》卡勒德·胡赛尼 - 互动提问，使用 #+问题，如 #你好 "
    type: interaction
    duration: 60
    idle_timing: 20
    idle_audios:
      1:
        type: audio
        name: "互动空闲时话术"
        value: "好了伙伴们，今天我们聊了阅读的那些事儿，那现在我们再一起来回顾一下前面介绍的十本畅销全球的书。今天我们推荐了能带你穿越时空，探索宇宙的奥秘的《时间简史》，温暖人心，治愈又感动的《解忧杂货店》，把人生的酸甜苦辣都写尽了的余华老师的《活着》，东野圭吾的悬疑大作《白夜行》，让你用全新视角看人类是怎么走过来的《人类简史》，讲述了一段关于友情、背叛和救赎的深刻故事的《追风筝的人》，魔幻现实主义的大作，文学经典《百年孤独》，对未来的思考《未来简史》，让你了解人工智能如何改变我们世界的《智能时代》，颠覆你的理财观念的《穷爸爸富爸爸》。相信每位朋友心中都有自己最喜欢的那一本，在此阅月也给大家带来史无前例的一次优惠折扣哦，现在只要在咱们直播间下单，这些畅销书都能享9.5折优惠哦！这种好事，千万别错过呀！对了，亲爱的朋友们，虽然阅读是个人的事，但分享感悟可是能让智慧加倍的哦。快在评论区告诉我，这些书给你带来了哪些启发？哪一本触动了你的心？咱们一起讨论吧，把阅读的快乐和收获分享给更多人。好了，今天参与活动的书籍有限，喜欢这些书的朋友，也记得抓紧时间享受折扣哦！"
    idle_start_audio:
      type: audio
      name: 口播过程中答复评论衔接语-出
      value: 好了。感谢小伙伴们的讨论，欢迎在评论区留言讨论哦，现在我们继续。
    idle_end_audio:
      type: audio
      name: 口播过程中答复评论衔接语-出
      value: 我看到评论区有小伙伴正在积极讨论。