version: 1
env:
  loop: true
  loop_times: 0
  log: true
  name: "book"
  # 开启弹幕监听，开启此功能，后续才可以使用on_barrage_received字段
  enable_barrage_monitoring: true
jobs:
  one_part:
    type: group
    name: 第一部分：畅销书推荐
    on_barrage_received:
      action: 'play_audio'
      opportunity: 'after_job_executed'
      # 解析的任务深度，如果为-1，则所有任务都可能响应此动作，如果为0，代表当前任务（不解析任何子任务），设置为正整数，那么会解析第n层的子任务（如果存在），例如这里设置为1，意为在每本图书执行完毕时，检查是否有弹幕然后执行相应操作
      deep: -1
      play_audio:
        type: audio
        name: '有弹幕时的过度内容'
        value: '感谢小伙伴的弹幕讨论，为保证直播内容的完整性，我们在后面的部分设置有讨论环节，现在先允许我继续介绍哦'
    background_image: "C:/Users/wukai/Downloads/1.png"
    jobs:
      1:
        type: group
        name: 《追风筝的人》卡勒德·胡赛尼
        caption: 《追风筝的人》卡勒德·胡赛尼
        background_music: "[充满魔法的背景音乐]"
        jobs:
          开始:
            name: 开始
            type: audio
            value: 亲爱的读者朋友们，大家好！今天，我为大家带来一本深触动人心弦、来自阿富汗的作家卡勒德·胡赛尼的作品——《追风筝的人》。这不仅仅是一本书，它更像是一段跨越时空的心灵之旅。
            background_image: "C:/Users/wukai/Downloads/2.png"
          结束:
            name: 结束
            type: audio
            value: 好了，亲爱的朋友们，如果你被《追风筝的人》的故事所打动，或是想要体验这段心灵旅程，请不要犹豫，现在就通过直播专属链接进行购买。同时，告诉你的亲朋好友，一起分享阅读的喜悦吧！
      2:
        type: group
        name: 《解忧杂货店》东野圭吾
        caption: 《解忧杂货店》东野圭吾
        background_music: "[轻快的科技感音乐作背景]"
        jobs:
          开始:
            name: 开始
            type: audio
            value: 今天我们要介绍的第二本书是来自日本作家东野圭吾的《解忧杂货店》。这是一部温暖人心的作品，它以一家看似普通的杂货店为线索，织出了一个个充满魔力的故事。
            background_image: "C:/Users/wukai/Downloads/3.png"
          书籍介绍:
            name: 书籍介绍
            type: audio
            value: 《解忧杂货店》讲述了一家名为“解忧杂货店”的神秘小店，通过回信的方式解决人们的各种烦恼。无论是爱情、家庭、学业还是工作上的问题，只需写信告知，隔天即可在牛奶箱中得到解答。
  second_part:
    name: 第二部分：特别话题讨论
    type: audio
    background_image: "C:/Users/wukai/Downloads/4.png"
    value: 阅读真的能够改变我们的生活，它能开阔我们的视野，提高我们的同理心。我个人非常喜欢在睡前读上几页，这有助于放松心情。你们有没有什么好的阅读习惯或心得想要跟大家分享？同时，我在这里也有几个阅读小贴士，比如制定阅读计划、选择适合的阅读环境等等。